### ISSUE TITLE
Token Grabber

### ISSUE THREAD

**Issue by 002-sans** [ItsK4P/Youtube-Views-Premium#2]
For each people who's reading this, it's just a token grabber :( don't try it.
Pour chaques personnes qui lit ça, c'est juste un token grabber :( n'essayez pas.

**Comment by Locksdsc** [comment]
à mon avis ça ne marche plus le grabber ça ft quand même 3 ans

**Comment by Locksdsc** [comment]
Mais en tout cas je sais que le script ne générera pas de views
